import { Oswald } from "next/font/google";

const oswald = Oswald({ subsets: ["latin"], weight: ["200", "400", "700"] });
import "./globals.css";

export const metadata = {
  title: "Movie Vault",
  description: "Generated by create next app",
  icons: {
    icon: "/popcorn-svgrepo-com.svg",
  },
  viewport: {
    // إضافة meta viewport
    width: "device-width",
    initialScale: 1,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.className}>{children}</body>
    </html>
  );
}
