export const metadata = {
  title: "Movie Vault",
  description: "Generated by create next app",
  icons: {
    icon: "/popcorn-svgrepo-com.svg",
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
};
